import pandas as pd
df=pd.read_csv("Indian_election_dataset.csv")
df.info()
df.drop('pc_no',axis=1,inplace=True)
df.drop('partyabbre',axis=1,inplace=True)
df.drop_duplicates(inplace=True)
df.rename(columns={"st_name":"state","pc_name":"parliamentry_consituency","cand_sex":"cand_gender","partyname":"party_name","totvotpoll":"Total_Votes_Polled"},inplace=True)
df.rename(columns={"pc_type":"consituency_type"},inplace=True)
df.info()
df= df.dropna(subset=['Total_Votes_Polled', 'electors','cand_gender'])
df.info()
df= df.dropna(subset=['Total_Votes_Polled', 'electors','cand_gender'])
df.info()
df['party_name'] = df['party_name'].fillna('Independent')
df['cand_name'] = df['cand_name'].fillna('Unknown')
df['consituency_type'] = df['consituency_type'].fillna(df['consituency_type'].mode()[0])
df['state'] = df['state'].fillna(df['state'].mode()[0])
df['year'] = df['year'].fillna(method='ffill')
df['cand_gender'] = df['cand_gender'].fillna('Unknown')
df.info()
df['parliamentry_consituency'] = df['parliamentry_consituency'].fillna(df['parliamentry_consituency'].mode()[0])
df.info()
df['cand_gender']=df['cand_gender'].astype("string")
df['cand_gender'] = df['cand_gender'].str.replace('M', 'Male')
df['cand_gender'] = df['cand_gender'].str.replace('F', 'Female')
df['cand_gender']=df['cand_gender'].str.replace('O','Other')
df["year"]=df["year"].astype("int")
df['state']=df['state'].astype("string")
df["parliamentry_consituency"]=df["parliamentry_consituency"].astype("string")
df["party_name"]=df["party_name"].astype("string")
df["party_name"]=df["party_name"].astype("string")
df["consituency_type"]=df["consituency_type"].astype("string")
df.info()
df["cand_name"]=df["cand_name"].astype("string")
df["Total_Votes_Polled"]=df["Total_Votes_Polled"].astype("int")
df["electors"]=df["electors"].astype("int")
df.info()
df.to_csv('election clean dataset.csv', index=False)


